-- AlterTable
ALTER TABLE "motorista" ADD COLUMN "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "motorista" ADD COLUMN "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

