-- ============================================
-- BACKUP COMPLETO DO BANCO DE DADOS
-- Data/Hora: 06/11/2025, 00:49:03
-- Timestamp: 06-11-2025-004903
-- Tipo: Backup Completo
-- Gerado via: API Backup Service
-- ============================================


-- Inserir dados na tabela prefeitura
-- Total de registros: 1

INSERT INTO prefeitura ("id", "nome", "cnpj", "imagem_perfil", "email_administrativo", "data_cadastro", "ativo", "requer_cupom_fiscal") VALUES (1, 'Prefeitura Municipal de São Paulo', '12345678000195', NULL, 'admin@prefeitura.sp.gov.br', '2025-10-21T02:33:43.851Z', true, true);


-- Inserir dados na tabela empresa
-- Total de registros: 1

INSERT INTO empresa ("id", "nome", "cnpj", "endereco", "uf", "contato", "ativo", "imagem_perfil", "isPublic", "tipo_empresa", "latitude", "longitude", "endereco_completo", "horario_funcionamento", "telefone", "email", "website", "bandeira", "servicos_disponiveis", "formas_pagamento", "avaliacao", "total_avaliacoes") VALUES (1, 'Posto Shell - Centro', '98765432000123', 'Rua das Flores, 123', 'SP', 'João Silva', true, NULL, true, 'POSTO_GASOLINA', -23.5505, -46.6333, 'Rua das Flores, 123, Centro, São Paulo - SP', '24h', '11999999999', 'contato@postoshell.com', NULL, 'Shell', 'Abastecimento, Lavagem, Conveniência', 'Dinheiro, Cartão, PIX', 4.5, 100);


-- Inserir dados na tabela usuario
-- Total de registros: 6

INSERT INTO usuario ("id", "prefeituraId", "email", "senha", "nome", "data_cadastro", "ultimo_login", "tipo_usuario", "empresaId", "imagem_perfil", "cpf", "phone", "statusAcess", "ativo") VALUES (3, 1, 'colaborador@prefeitura.sp.gov.br', '$2a$12$PpvL.wl8qAmt2k4b/lWyRO3epTXFUkynM3crXmN6HfPpi6ZWCjI5a', 'Colaborador da Prefeitura', '2025-10-21T02:33:43.924Z', NULL, 'COLABORADOR_PREFEITURA', NULL, NULL, '22222222222', NULL, 'Ativado', true);
INSERT INTO usuario ("id", "prefeituraId", "email", "senha", "nome", "data_cadastro", "ultimo_login", "tipo_usuario", "empresaId", "imagem_perfil", "cpf", "phone", "statusAcess", "ativo") VALUES (4, NULL, 'admin@postoshell.com', '$2a$12$PpvL.wl8qAmt2k4b/lWyRO3epTXFUkynM3crXmN6HfPpi6ZWCjI5a', 'Administrador da Empresa', '2025-10-21T02:33:43.941Z', NULL, 'ADMIN_EMPRESA', 1, NULL, '33333333333', NULL, 'Ativado', true);
INSERT INTO usuario ("id", "prefeituraId", "email", "senha", "nome", "data_cadastro", "ultimo_login", "tipo_usuario", "empresaId", "imagem_perfil", "cpf", "phone", "statusAcess", "ativo") VALUES (5, NULL, 'colaborador@postoshell.com', '$2a$12$PpvL.wl8qAmt2k4b/lWyRO3epTXFUkynM3crXmN6HfPpi6ZWCjI5a', 'Colaborador da Empresa', '2025-10-21T02:33:43.960Z', NULL, 'COLABORADOR_EMPRESA', 1, NULL, '44444444444', NULL, 'Ativado', true);
INSERT INTO usuario ("id", "prefeituraId", "email", "senha", "nome", "data_cadastro", "ultimo_login", "tipo_usuario", "empresaId", "imagem_perfil", "cpf", "phone", "statusAcess", "ativo") VALUES (6, NULL, 'olivalpaulinocc@gmail.com', '$2a$12$.fYDfUTexFumX6ZmIxxUTOceNEFGqehxDjWQu.UP.bknlpHtS2GUy', 'Olival Paulino', '2025-10-21T18:43:22.165Z', NULL, 'SUPER_ADMIN', NULL, NULL, '12345678902', NULL, 'Acesso_solicitado', true);
INSERT INTO usuario ("id", "prefeituraId", "email", "senha", "nome", "data_cadastro", "ultimo_login", "tipo_usuario", "empresaId", "imagem_perfil", "cpf", "phone", "statusAcess", "ativo") VALUES (2, 1, 'admin@prefeitura.sp.gov.br', '$2a$12$PpvL.wl8qAmt2k4b/lWyRO3epTXFUkynM3crXmN6HfPpi6ZWCjI5a', 'Administrador da Prefeitura', '2025-10-21T02:33:43.908Z', '2025-10-31T20:00:00.904Z', 'ADMIN_PREFEITURA', NULL, NULL, '11111111111', NULL, 'Ativado', true);
INSERT INTO usuario ("id", "prefeituraId", "email", "senha", "nome", "data_cadastro", "ultimo_login", "tipo_usuario", "empresaId", "imagem_perfil", "cpf", "phone", "statusAcess", "ativo") VALUES (1, NULL, 'superadmin@nordev.com', '$2a$12$PpvL.wl8qAmt2k4b/lWyRO3epTXFUkynM3crXmN6HfPpi6ZWCjI5a', 'Super Administrador', '2025-10-21T02:33:43.707Z', '2025-11-06T03:48:36.782Z', 'SUPER_ADMIN', NULL, NULL, '00000000000', NULL, 'Ativado', true);


-- Inserir dados na tabela orgao
-- Total de registros: 1

INSERT INTO orgao ("id", "prefeituraId", "nome", "sigla", "ativo") VALUES (1, 1, 'Secretaria Municipal de Saúde', 'SMS', true);


-- Inserir dados na tabela veiculo
-- Total de registros: 1

INSERT INTO veiculo ("id", "prefeituraId", "orgaoId", "contaFaturamentoOrgaoId", "nome", "placa", "modelo", "ano", "tipo_abastecimento", "ativo", "capacidade_tanque", "tipo_veiculo", "situacao_veiculo", "observacoes", "periodicidade", "quantidade", "apelido", "ano_fabricacao", "chassi", "renavam", "crlv", "crlv_vencimento", "tacografo", "foto_veiculo", "foto_crlv", "cor", "capacidade_passageiros") VALUES (1, 1, 1, NULL, 'Ambulância 01', 'ABC-1234', 'Ford Transit', 2020, 'COTA', true, 80, 'Ambulancia', 'Proprio', 'Veículo em excelente estado de conservação', 'Semanal', 100, 'Ambulância da Saúde', 2019, '9BWZZZZZZZZZZZZZZ', '12345678901', NULL, NULL, NULL, NULL, NULL, 'Branco', 8);


-- Inserir dados na tabela motorista
-- Total de registros: 1

INSERT INTO motorista ("id", "prefeituraId", "nome", "cpf", "cnh", "categoria_cnh", "data_vencimento_cnh", "telefone", "email", "endereco", "imagem_perfil", "ativo", "observacoes") VALUES (1, 1, 'João Silva', '55555555555', '12345678901', 'B', '2025-12-31T00:00:00.000Z', '11988888888', 'joao.silva@prefeitura.sp.gov.br', 'Rua das Palmeiras, 456', NULL, true, 'Motorista experiente com 10 anos de experiência');


-- Inserir dados na tabela categoria
-- Total de registros: 3

INSERT INTO categoria ("id", "prefeituraId", "tipo_categoria", "nome", "descricao", "ativo") VALUES (1, 1, 'VEICULO', 'Ambulâncias', 'Veículos de emergência médica', true);
INSERT INTO categoria ("id", "prefeituraId", "tipo_categoria", "nome", "descricao", "ativo") VALUES (2, 1, 'VEICULO', 'Veículos Administrativos', 'Veículos para uso administrativo', true);
INSERT INTO categoria ("id", "prefeituraId", "tipo_categoria", "nome", "descricao", "ativo") VALUES (3, 1, 'MOTORISTA', 'Motoristas de Emergência', 'Motoristas habilitados para veículos de emergência', true);


-- Inserir dados na tabela combustivel
-- Total de registros: 4

INSERT INTO combustivel ("id", "nome", "sigla", "descricao", "ativo", "observacoes") VALUES (1, 'Gasolina Comum', 'GAS_COMUM', 'Gasolina comum para veículos leves', true, NULL);
INSERT INTO combustivel ("id", "nome", "sigla", "descricao", "ativo", "observacoes") VALUES (2, 'Gasolina Aditivada', 'GAS_ADITIVADA', 'Gasolina com aditivos para melhor performance', true, NULL);
INSERT INTO combustivel ("id", "nome", "sigla", "descricao", "ativo", "observacoes") VALUES (3, 'Etanol', 'ETANOL', 'Etanol hidratado para veículos flex', true, NULL);
INSERT INTO combustivel ("id", "nome", "sigla", "descricao", "ativo", "observacoes") VALUES (4, 'Diesel S10', 'DIESEL_S10', 'Diesel com baixo teor de enxofre', true, NULL);


-- Inserir dados na tabela anp_semana
-- Total de registros: 1

INSERT INTO anp_semana ("id", "semana_ref", "publicada_em", "ativo", "observacoes", "importado_em") VALUES (1, '2025-08-24T00:00:00.000Z', '2025-08-30T10:00:00.000Z', false, 'Semana de referência 24/08/2025 a 30/08/2025', '2025-08-30T15:30:00.000Z');


-- Inserir dados na tabela anp_precos_uf
-- Total de registros: 177

INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (1, 1, 'AC', 'ETANOL_COMUM', 5.95, 5.99, 6.08, 6.32, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (2, 1, 'AL', 'ETANOL_COMUM', 4.99, 5.02, 5.49, 5.3, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (3, 1, 'AP', 'ETANOL_COMUM', 5.33, 5.43, 5.59, 5.73, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (4, 1, 'AM', 'ETANOL_COMUM', 5.47, 5.49, 5.59, 5.79, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (5, 1, 'BA', 'ETANOL_COMUM', 4.19, 4.75, 5.19, 5.01, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (6, 1, 'CE', 'ETANOL_COMUM', 4.59, 5.02, 5.62, 5.3, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (7, 1, 'DF', 'ETANOL_COMUM', 4.25, 4.53, 4.76, 4.78, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (8, 1, 'ES', 'ETANOL_COMUM', 4.05, 4.37, 4.99, 4.61, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (9, 1, 'GO', 'ETANOL_COMUM', 3.59, 3.94, 4.79, 4.16, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (10, 1, 'MA', 'ETANOL_COMUM', 4.45, 4.73, 5.79, 4.99, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (11, 1, 'MT', 'ETANOL_COMUM', 3.63, 4.15, 4.31, 4.38, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (12, 1, 'MS', 'ETANOL_COMUM', 3.55, 3.86, 4.92, 4.07, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (13, 1, 'MG', 'ETANOL_COMUM', 3.68, 4.17, 4.89, 4.4, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (14, 1, 'PA', 'ETANOL_COMUM', 4.29, 4.76, 5.29, 5.02, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (15, 1, 'PB', 'ETANOL_COMUM', 4.37, 4.49, 4.89, 4.74, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (16, 1, 'PR', 'ETANOL_COMUM', 3.69, 4.39, 4.94, 4.63, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (17, 1, 'PE', 'ETANOL_COMUM', 4.34, 4.84, 6.49, 5.11, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (18, 1, 'PI', 'ETANOL_COMUM', 4.29, 4.53, 5.2, 4.78, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (19, 1, 'RJ', 'ETANOL_COMUM', 3.89, 4.42, 5.49, 4.66, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (20, 1, 'RN', 'ETANOL_COMUM', 4.79, 5.09, 5.6, 5.37, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (21, 1, 'RS', 'ETANOL_COMUM', 4.15, 4.73, 5.99, 4.99, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (22, 1, 'RO', 'ETANOL_COMUM', 4.69, 4.96, 5.99, 5.23, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (23, 1, 'RR', 'ETANOL_COMUM', 5.15, 5.15, 5.2, 5.43, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (24, 1, 'SC', 'ETANOL_COMUM', 4.09, 4.59, 5.49, 4.84, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (25, 1, 'SP', 'ETANOL_COMUM', 3.19, 3.98, 6.29, 4.2, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (26, 1, 'SE', 'ETANOL_COMUM', 4.9, 4.95, 4.99, 5.22, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (27, 1, 'TO', 'ETANOL_COMUM', 4.37, 4.77, 5.19, 5.03, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (28, 1, 'AC', 'GASOLINA_ADITIVADA', 8.07, 8.16, 8.29, 8.61, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (29, 1, 'AL', 'GASOLINA_ADITIVADA', 6.13, 6.37, 6.69, 6.72, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (30, 1, 'AP', 'GASOLINA_ADITIVADA', 6.14, 6.29, 6.42, 6.64, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (31, 1, 'AM', 'GASOLINA_ADITIVADA', 6.99, 7.05, 8.39, 7.44, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (32, 1, 'BA', 'GASOLINA_ADITIVADA', 5.59, 6.47, 6.99, 6.83, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (33, 1, 'CE', 'GASOLINA_ADITIVADA', 5.89, 6.48, 6.89, 6.84, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (34, 1, 'DF', 'GASOLINA_ADITIVADA', 6.24, 6.5, 6.85, 6.86, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (35, 1, 'ES', 'GASOLINA_ADITIVADA', 5.77, 6.1, 6.79, 6.44, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (36, 1, 'GO', 'GASOLINA_ADITIVADA', 5.59, 6.14, 6.87, 6.48, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (37, 1, 'MA', 'GASOLINA_ADITIVADA', 5.59, 6.07, 7.29, 6.4, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (38, 1, 'MT', 'GASOLINA_ADITIVADA', 6.08, 6.48, 6.79, 6.84, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (39, 1, 'MS', 'GASOLINA_ADITIVADA', 5.61, 6.12, 7.03, 6.46, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (40, 1, 'MG', 'GASOLINA_ADITIVADA', 5.69, 6.35, 7.18, 6.7, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (41, 1, 'PA', 'GASOLINA_ADITIVADA', 5.69, 6.5, 7.29, 6.86, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (42, 1, 'PB', 'GASOLINA_ADITIVADA', 5.79, 6.11, 6.39, 6.45, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (43, 1, 'PR', 'GASOLINA_ADITIVADA', 5.69, 6.6, 7.19, 6.96, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (44, 1, 'PE', 'GASOLINA_ADITIVADA', 5.43, 6.52, 6.94, 6.88, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (45, 1, 'PI', 'GASOLINA_ADITIVADA', 5.69, 6.08, 6.45, 6.41, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (46, 1, 'RJ', 'GASOLINA_ADITIVADA', 5.49, 6.28, 7.79, 6.63, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (47, 1, 'RN', 'GASOLINA_ADITIVADA', 5.98, 6.32, 6.99, 6.67, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (48, 1, 'RS', 'GASOLINA_ADITIVADA', 5.49, 6.19, 7.49, 6.53, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (49, 1, 'RO', 'GASOLINA_ADITIVADA', 6.09, 6.78, 7.09, 7.15, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (50, 1, 'RR', 'GASOLINA_ADITIVADA', 6.99, 7.05, 7.1, 7.44, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (51, 1, 'SC', 'GASOLINA_ADITIVADA', 5.97, 6.47, 6.89, 6.83, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (52, 1, 'SP', 'GASOLINA_ADITIVADA', 5.19, 6.37, 9.49, 6.72, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (53, 1, 'SE', 'GASOLINA_ADITIVADA', 6.62, 6.75, 7.01, 7.12, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (54, 1, 'TO', 'GASOLINA_ADITIVADA', 6.19, 6.67, 7.19, 7.04, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (55, 1, 'AC', 'GASOLINA_COMUM', 8.07, 8.08, 8.09, 8.52, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (56, 1, 'AL', 'GASOLINA_COMUM', 6.09, 6.15, 6.49, 6.49, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (57, 1, 'AP', 'GASOLINA_COMUM', 5.95, 5.99, 6.19, 6.32, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (58, 1, 'AM', 'GASOLINA_COMUM', 6.98, 7.03, 8.29, 7.42, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (59, 1, 'BA', 'GASOLINA_COMUM', 5.56, 6.28, 6.69, 6.63, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (60, 1, 'CE', 'GASOLINA_COMUM', 5.74, 6.34, 6.75, 6.69, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (61, 1, 'DF', 'GASOLINA_COMUM', 6.02, 6.45, 6.58, 6.8, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (62, 1, 'ES', 'GASOLINA_COMUM', 5.57, 5.91, 6.69, 6.24, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (63, 1, 'GO', 'GASOLINA_COMUM', 5.49, 5.98, 6.59, 6.31, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (64, 1, 'MA', 'GASOLINA_COMUM', 5.55, 5.93, 7.09, 6.26, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (65, 1, 'MT', 'GASOLINA_COMUM', 5.73, 6.29, 6.71, 6.64, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (66, 1, 'MS', 'GASOLINA_COMUM', 5.56, 5.93, 6.89, 6.26, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (67, 1, 'MG', 'GASOLINA_COMUM', 5.59, 6.09, 6.78, 6.42, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (68, 1, 'PA', 'GASOLINA_COMUM', 5.59, 6.23, 7.15, 6.57, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (69, 1, 'PB', 'GASOLINA_COMUM', 5.65, 5.95, 6.29, 6.28, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (70, 1, 'PR', 'GASOLINA_COMUM', 5.69, 6.49, 6.99, 6.85, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (71, 1, 'PE', 'GASOLINA_COMUM', 5.39, 6.31, 7.59, 6.66, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (72, 1, 'PI', 'GASOLINA_COMUM', 5.64, 5.82, 6.39, 6.14, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (73, 1, 'RJ', 'GASOLINA_COMUM', 5.49, 6.02, 7.79, 6.35, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (74, 1, 'RN', 'GASOLINA_COMUM', 5.98, 6.26, 6.79, 6.6, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (75, 1, 'RS', 'GASOLINA_COMUM', 5.49, 5.98, 7.24, 6.31, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (76, 1, 'RO', 'GASOLINA_COMUM', 5.89, 6.58, 7.06, 6.94, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (77, 1, 'RR', 'GASOLINA_COMUM', 6.95, 6.95, 6.95, 7.33, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (78, 1, 'SC', 'GASOLINA_COMUM', 5.84, 6.33, 6.79, 6.68, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (79, 1, 'SP', 'GASOLINA_COMUM', 5.09, 6.04, 8.99, 6.37, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (80, 1, 'SE', 'GASOLINA_COMUM', 6.62, 6.64, 6.69, 7.01, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (81, 1, 'TO', 'GASOLINA_COMUM', 5.83, 6.55, 6.87, 6.91, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (82, 1, 'AL', 'GLP', 84.99, 101.84, 115, 107.44, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (83, 1, 'AP', 'GLP', 115, 121.07, 132, 127.73, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (84, 1, 'AM', 'GLP', 118, 123.75, 140, 130.56, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (85, 1, 'BA', 'GLP', 100, 116.38, 148, 122.78, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (86, 1, 'CE', 'GLP', 99.98, 106.73, 123, 112.6, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (87, 1, 'DF', 'GLP', 92.99, 102.3, 112, 107.93, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (88, 1, 'ES', 'GLP', 85.99, 96.95, 120, 102.28, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (89, 1, 'GO', 'GLP', 89.99, 108.38, 130, 114.34, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (90, 1, 'MA', 'GLP', 109.99, 118.59, 130, 125.11, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (91, 1, 'MT', 'GLP', 94.99, 115.97, 140, 122.35, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (92, 1, 'MS', 'GLP', 95, 110.53, 138, 116.61, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (93, 1, 'MG', 'GLP', 85, 104.78, 142, 110.54, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (94, 1, 'PA', 'GLP', 104, 112.24, 120, 118.41, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (95, 1, 'PB', 'GLP', 84.99, 101.68, 115, 107.27, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (96, 1, 'PR', 'GLP', 91.9, 104.21, 125, 109.94, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (97, 1, 'PE', 'GLP', 80, 94.5, 115, 99.7, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (98, 1, 'PI', 'GLP', 100, 104.44, 115, 110.18, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (99, 1, 'RJ', 'GLP', 80, 95.49, 120, 100.74, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (100, 1, 'RN', 'GLP', 90, 103, 128, 108.66, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (101, 1, 'RS', 'GLP', 99, 112.08, 130, 118.24, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (102, 1, 'RO', 'GLP', 107, 118.72, 130, 125.25, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (103, 1, 'RR', 'GLP', 130, 138.43, 156, 146.04, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (104, 1, 'SC', 'GLP', 104.9, 118.94, 135, 125.48, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (105, 1, 'SP', 'GLP', 81.99, 110.1, 139, 116.16, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (106, 1, 'SE', 'GLP', 96, 103.5, 110, 109.19, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (107, 1, 'TO', 'GLP', 110, 124.46, 130, 131.31, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (108, 1, 'AL', 'GNV', 4.59, 4.59, 4.59, 4.84, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (109, 1, 'AM', 'GNV', 4.59, 4.59, 4.59, 4.84, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (110, 1, 'BA', 'GNV', 3.99, 4.12, 5.79, 4.35, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (111, 1, 'CE', 'GNV', 4.85, 5.11, 5.15, 5.39, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (112, 1, 'ES', 'GNV', 4.09, 4.28, 4.49, 4.52, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (113, 1, 'MT', 'GNV', 4.05, 4.05, 4.05, 4.27, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (114, 1, 'MS', 'GNV', 4.59, 4.59, 4.59, 4.84, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (115, 1, 'MG', 'GNV', 4.29, 5.16, 5.39, 5.44, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (116, 1, 'PB', 'GNV', 4.85, 4.86, 5.21, 5.13, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (117, 1, 'PR', 'GNV', 4.54, 4.69, 4.69, 4.95, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (118, 1, 'PE', 'GNV', 4.39, 4.39, 4.39, 4.63, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (119, 1, 'RJ', 'GNV', 3.97, 4.38, 6.28, 4.62, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (120, 1, 'RN', 'GNV', 5.09, 5.19, 5.19, 5.48, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (121, 1, 'RS', 'GNV', 4.69, 4.84, 5.34, 5.11, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (122, 1, 'SC', 'GNV', 4.59, 4.84, 5.29, 5.11, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (123, 1, 'SP', 'GNV', 4.09, 4.59, 5.29, 4.84, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (124, 1, 'SE', 'GNV', 4.69, 4.69, 4.69, 4.95, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (125, 1, 'AC', 'DIESEL_S500', 8.17, 8.17, 8.19, 8.62, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (126, 1, 'AL', 'DIESEL_S500', 5.69, 6.02, 6.35, 6.35, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (127, 1, 'AP', 'DIESEL_S500', 6.3, 6.39, 6.48, 6.74, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (128, 1, 'AM', 'DIESEL_S500', 6.49, 6.49, 6.59, 6.85, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (129, 1, 'BA', 'DIESEL_S500', 5.59, 5.94, 6.75, 6.27, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (130, 1, 'CE', 'DIESEL_S500', 5.59, 6.05, 6.69, 6.38, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (131, 1, 'DF', 'DIESEL_S500', 5.87, 6.05, 6.28, 6.38, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (132, 1, 'ES', 'DIESEL_S500', 5.79, 5.91, 6.39, 6.24, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (133, 1, 'GO', 'DIESEL_S500', 5.49, 5.92, 7.06, 6.25, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (134, 1, 'MA', 'DIESEL_S500', 5.54, 5.88, 6.69, 6.2, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (135, 1, 'MT', 'DIESEL_S500', 5.79, 6.29, 6.89, 6.64, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (136, 1, 'MS', 'DIESEL_S500', 5.64, 6.03, 7.29, 6.36, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (137, 1, 'MG', 'DIESEL_S500', 5.45, 5.87, 6.49, 6.19, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (138, 1, 'PA', 'DIESEL_S500', 5.58, 6.38, 7.24, 6.73, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (139, 1, 'PB', 'DIESEL_S500', 5.45, 5.59, 6.29, 5.9, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (140, 1, 'PR', 'DIESEL_S500', 5.49, 5.9, 6.77, 6.22, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (141, 1, 'PE', 'DIESEL_S500', 5.59, 5.97, 5.97, 6.3, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (142, 1, 'PI', 'DIESEL_S500', 5.64, 5.92, 6.24, 6.25, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (143, 1, 'RJ', 'DIESEL_S500', 5.42, 6, 6.99, 6.33, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (144, 1, 'RN', 'DIESEL_S500', 5.69, 6.02, 6.99, 6.35, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (145, 1, 'RS', 'DIESEL_S500', 5.49, 6.06, 7.14, 6.39, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (146, 1, 'RO', 'DIESEL_S500', 6.09, 6.36, 7.09, 6.71, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (147, 1, 'RR', 'DIESEL_S500', 6.8, 6.84, 6.94, 7.22, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (148, 1, 'SC', 'DIESEL_S500', 5.49, 6.09, 6.73, 6.42, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (149, 1, 'SP', 'DIESEL_S500', 5.35, 6.04, 7.99, 6.37, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (150, 1, 'TO', 'DIESEL_S500', 5.49, 6.1, 6.79, 6.44, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (151, 1, 'AC', 'DIESEL_S10', 8.17, 8.18, 8.19, 8.63, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (152, 1, 'AL', 'DIESEL_S10', 5.59, 5.84, 6.29, 6.16, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (153, 1, 'AP', 'DIESEL_S10', 6.32, 6.49, 6.61, 6.85, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (154, 1, 'AM', 'DIESEL_S10', 6.49, 6.56, 8.39, 6.92, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (155, 1, 'BA', 'DIESEL_S10', 5.68, 6.06, 6.89, 6.39, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (156, 1, 'CE', 'DIESEL_S10', 5.43, 5.84, 6.79, 6.16, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (157, 1, 'DF', 'DIESEL_S10', 5.87, 6.04, 6.29, 6.37, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (158, 1, 'ES', 'DIESEL_S10', 5.76, 6, 6.49, 6.33, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (159, 1, 'GO', 'DIESEL_S10', 5.59, 6.01, 7.17, 6.34, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (160, 1, 'MA', 'DIESEL_S10', 5.47, 5.89, 6.99, 6.21, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (161, 1, 'MT', 'DIESEL_S10', 5.85, 6.32, 6.99, 6.67, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (162, 1, 'MS', 'DIESEL_S10', 5.68, 6.05, 7.27, 6.38, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (163, 1, 'MG', 'DIESEL_S10', 5.59, 5.98, 6.89, 6.31, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (164, 1, 'PA', 'DIESEL_S10', 5.49, 6.19, 7.29, 6.53, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (165, 1, 'PB', 'DIESEL_S10', 5.57, 5.71, 6.32, 6.02, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (166, 1, 'PR', 'DIESEL_S10', 5.49, 6.07, 6.99, 6.4, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (167, 1, 'PE', 'DIESEL_S10', 5.39, 5.72, 6.99, 6.03, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (168, 1, 'PI', 'DIESEL_S10', 5.69, 6, 6.79, 6.33, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (169, 1, 'RJ', 'DIESEL_S10', 5.52, 6.09, 7.39, 6.42, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (170, 1, 'RN', 'DIESEL_S10', 5.49, 6, 6.99, 6.33, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (171, 1, 'RS', 'DIESEL_S10', 5.49, 6.16, 7.29, 6.5, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (172, 1, 'RO', 'DIESEL_S10', 5.99, 6.38, 7.29, 6.73, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (173, 1, 'RR', 'DIESEL_S10', 6.85, 6.86, 6.95, 7.24, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (174, 1, 'SC', 'DIESEL_S10', 5.59, 6.13, 6.83, 6.47, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (175, 1, 'SP', 'DIESEL_S10', 5.46, 6.15, 9.29, 6.49, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (176, 1, 'SE', 'DIESEL_S10', 5.64, 5.86, 6.28, 6.18, 'MEDIO', 5.5);
INSERT INTO anp_precos_uf ("id", "anp_semana_id", "uf", "combustivel", "preco_minimo", "preco_medio", "preco_maximo", "teto_calculado", "base_utilizada", "margem_aplicada") VALUES (177, 1, 'TO', 'DIESEL_S10', 5.49, 6.07, 6.47, 6.4, 'MEDIO', 5.5);


-- Inserir dados na tabela parametros_teto
-- Total de registros: 1

INSERT INTO parametros_teto ("id", "anp_base", "margem_pct", "excecoes_combustivel", "ativo", "observacoes") VALUES (1, 'MEDIO', 5.5, 'Gasolina comum sem margem aplicada', true, 'Parâmetro padrão para cálculo de teto de preços');


-- Inserir dados na tabela refresh_token
-- Total de registros: 15

INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (1, 1, 'c3eb96408cae802e9fdd9d813f05760b4ccc75bd6931689b73e288cd431b937c', '2025-10-29T00:53:09.323Z', '2025-10-22T00:53:09.323Z', '2025-10-22T01:31:48.656Z', NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (2, 1, '48f7d451a4d137f0b52303c6dd8af0996d396b1c9447b282164bc9351d4300f2', '2025-10-29T01:31:48.702Z', '2025-10-22T01:31:48.702Z', '2025-10-22T01:46:07.196Z', NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (3, 2, 'dcd85852085ae7245f2c0ef9536424a3771be5dff7a885c91c25b93e82dade8b', '2025-11-07T20:00:00.984Z', '2025-10-31T20:00:00.984Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (4, 1, 'f50bc26005b4433f109cd3af16f2fdf6f413a82e386c039ef15f62919842f999', '2025-11-12T14:12:37.831Z', '2025-11-05T14:12:37.831Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (5, 1, '0d8d53d2c7229d2f022111c03a893705b5d81efe6bd72a55bbf50655b16332aa', '2025-11-12T14:28:50.051Z', '2025-11-05T14:28:50.051Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (6, 1, 'ba9f534e3c8a9b50e6384a91cf380db4b7a56a06481fb97d9bf12df13f4b9ac8', '2025-11-12T14:29:49.688Z', '2025-11-05T14:29:49.688Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (7, 1, 'fa589e9d3fcfb39e4e2193666246cd6b5ddebb66386dc81ebc443f246308f2e6', '2025-11-12T14:35:41.401Z', '2025-11-05T14:35:41.401Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (8, 1, 'f91389e2416d57c28b9b6255b28e7ce6ece0fa2344da65e747f2a4d42a0d7cb0', '2025-11-12T14:46:36.912Z', '2025-11-05T14:46:36.912Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (9, 1, '4611a03f504b8cb31ccf404be69773e09d47a0778bb3fc8b1745d29d8e1b0e26', '2025-11-12T14:51:04.603Z', '2025-11-05T14:51:04.603Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (10, 1, 'c85abec7ac17b41d5d3eebbcdb4642b2362223b20cee12a6a8467c1c7979a2ec', '2025-11-12T14:55:48.578Z', '2025-11-05T14:55:48.579Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (11, 1, 'c3793502436fff1a5d17359246d038c4d3f43e5839a5968dbddfafdc1a2743db', '2025-11-12T15:08:38.695Z', '2025-11-05T15:08:38.696Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (12, 1, 'cb5a5ce875102513ba8743c659eb8fcb568552780b7474a6af1eabe51148bab0', '2025-11-13T03:40:42.877Z', '2025-11-06T03:40:42.878Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (13, 1, '090e7bea2543950a54433df3f63cee6a72f86ce117bcf12dcb3b5c4ed4d745ba', '2025-11-13T03:43:24.444Z', '2025-11-06T03:43:24.444Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (14, 1, 'e1d67c49999af3740456a057205699919c36c1bad0aa6b54ea27095916bcc83e', '2025-11-13T03:48:19.204Z', '2025-11-06T03:48:19.204Z', NULL, NULL, NULL, NULL);
INSERT INTO refresh_token ("id", "usuarioId", "token", "expiracao", "criadoEm", "revogadoEm", "ipCriacao", "ipRevogacao", "userAgent") VALUES (15, 1, '7f2ead923204cadbc13a7445fcd36d3f11c6e5a66e8c01a8d96a60d63eaa17b9', '2025-11-13T03:48:36.792Z', '2025-11-06T03:48:36.792Z', NULL, NULL, NULL, NULL);

