-- AlterTable: Adicionar created_date e modified_date em todas as tabelas
-- Data: 2025-11-18

-- Prefeitura
ALTER TABLE "prefeitura" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "prefeitura" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Usuario
ALTER TABLE "usuario" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "usuario" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Empresa
ALTER TABLE "empresa" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "empresa" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Orgao
ALTER TABLE "orgao" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "orgao" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Contrato
ALTER TABLE "contrato" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "contrato" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Combustivel
ALTER TABLE "combustivel" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "combustivel" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Categoria
ALTER TABLE "categoria" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "categoria" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Veiculo
ALTER TABLE "veiculo" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "veiculo" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Abastecimento
ALTER TABLE "abastecimento" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "abastecimento" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CotaOrgao
ALTER TABLE "cota_orgao" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "cota_orgao" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ContaFaturamentoOrgao
ALTER TABLE "conta_faturamento_orgao" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "conta_faturamento_orgao" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Processo
ALTER TABLE "processo" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "processo" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ContratoCombustivel
ALTER TABLE "contrato_combustivel" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "contrato_combustivel" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- VeiculoCombustivel
ALTER TABLE "veiculo_combustivel" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "veiculo_combustivel" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- VeiculoCategoria
ALTER TABLE "veiculo_categoria" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "veiculo_categoria" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- VeiculoMotorista
ALTER TABLE "veiculo_motorista" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "veiculo_motorista" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- UsuarioOrgao
ALTER TABLE "usuario_orgao" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "usuario_orgao" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ProcessoCombustivel
ALTER TABLE "processo_combustivel" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "processo_combustivel" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ProcessoCombustivelConsorciado
ALTER TABLE "processo_combustivel_consorciado" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "processo_combustivel_consorciado" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ProcessoPrefeituraConsorcio
ALTER TABLE "processo_prefeitura_consorcio" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "processo_prefeitura_consorcio" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ProcessoPrefeituraCombustivelConsorcio
ALTER TABLE "processo_prefeitura_combustivel_consorcio" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "processo_prefeitura_combustivel_consorcio" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- EmpresaPrecoCombustivel
ALTER TABLE "empresa_preco_combustivel" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "empresa_preco_combustivel" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AditivoContrato
ALTER TABLE "aditivo_contrato" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "aditivo_contrato" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AditivoProcesso
ALTER TABLE "aditivo_processo" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "aditivo_processo" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AnpSemana
ALTER TABLE "anp_semana" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "anp_semana" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AnpPrecosUf
ALTER TABLE "anp_precos_uf" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "anp_precos_uf" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- LogsAlteracoes
ALTER TABLE "logs_alteracoes" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "logs_alteracoes" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Notificacao
ALTER TABLE "notificacao" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "notificacao" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- OnOff
ALTER TABLE "onoff" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "onoff" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- OnOffApp
ALTER TABLE "onoffapp" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "onoffapp" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ParametrosTeto
ALTER TABLE "parametros_teto" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "parametros_teto" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- RefreshToken
ALTER TABLE "refresh_token" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "refresh_token" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- SolicitacaoAbastecimento
ALTER TABLE "solicitacoes_abastecimento" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "solicitacoes_abastecimento" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- VeiculoCotaPeriodo
ALTER TABLE "veiculo_cota_periodo" ADD COLUMN IF NOT EXISTS "created_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "veiculo_cota_periodo" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- SolicitacoesQrCodeVeiculo (já tem data_cadastro, só adiciona modified_date)
ALTER TABLE "solicitacoes_qrcode_veiculo" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- QrCodeMotorista (já tem data_cadastro, só adiciona modified_date)
ALTER TABLE "qrcode_motorista" ADD COLUMN IF NOT EXISTS "modified_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Criar trigger para atualizar modified_date automaticamente em todas as tabelas
-- Nota: O Prisma @updatedAt já faz isso automaticamente, mas garantimos com trigger também

CREATE OR REPLACE FUNCTION update_modified_date()
RETURNS TRIGGER AS $$
BEGIN
    NEW.modified_date = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Aplicar trigger em todas as tabelas (exceto Motorista que já tem @updatedAt)
-- O Prisma gerencia isso automaticamente, mas o trigger garante consistência

